name: Build and Deploy
on:
  push:
    branches: ["develop"]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build
        env:
          VITE_CTP_API_URL: ${{ secrets.VITE_CTP_API_URL }}
          VITE_CTP_AUTH_URL: ${{ secrets.VITE_CTP_AUTH_URL }}
          VITE_CTP_CLIENT_ID: ${{ secrets.VITE_CTP_CLIENT_ID }}
          VITE_CTP_CLIENT_SECRET: ${{ secrets.VITE_CTP_CLIENT_SECRET }}
          VITE_CTP_PROJECT_KEY: ${{ secrets.VITE_CTP_PROJECT_KEY }}
          VITE_CTP_SCOPES: ${{ secrets.VITE_CTP_SCOPES }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
